apiVersion: v1
kind: Service
metadata:
  name: drupal-svc
  labels:
    app: drupal-svc
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: drupal
